server:
  port: 8090

spring:
  application:
    name: Tanos
  datasource:
    url: jdbc:postgresql://localhost:5432/tanosdb?createDatabaseIfNotExist=true
    username: postgres
    password: 123456789
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages